/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.telas;

import br.edu.calculadora.CalculadoraNormal;
import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.awt.Color;

/**
 *
 * @author Alunos
 */
public class TelaCalculadora extends javax.swing.JFrame {

    private CalculadoraNormal calculadoraNormal;

    public CalculadoraNormal getCalculadoraNormal() {
        return calculadoraNormal;
    }

    public void setCalculadoraNormal(CalculadoraNormal calcNormal) {
        calculadoraNormal = calcNormal;
    }

    /**
     * Creates new form TelaCalculadora
     */
    public TelaCalculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CalculadoraMenu = new javax.swing.JTabbedPane();
        TelaNormal = new javax.swing.JPanel();
        inputCalculator = new javax.swing.JTextField();
        btnDEL = new javax.swing.JButton();
        btnAC = new javax.swing.JButton();
        btnPerc = new javax.swing.JButton();
        btnDiv = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnMenos = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btnMais = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnIgual = new javax.swing.JButton();
        btnPonto = new javax.swing.JButton();
        btnMulti = new javax.swing.JButton();
        TelaCientifica = new javax.swing.JTabbedPane();
        TelaIMC = new javax.swing.JTabbedPane();
        MenuBar = new javax.swing.JMenuBar();
        btnSobre = new javax.swing.JMenu();
        btnAjuda = new javax.swing.JMenu();
        btnHistorico = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        CalculadoraMenu.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        TelaNormal.setBackground(new java.awt.Color(255, 255, 255));
        TelaNormal.setOpaque(false);
        TelaNormal.setPreferredSize(new java.awt.Dimension(400, 450));

        inputCalculator.setEditable(false);
        inputCalculator.setFont(new java.awt.Font("Dialog", 1, 32)); // NOI18N
        inputCalculator.setForeground(new java.awt.Color(255, 255, 255));
        inputCalculator.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        inputCalculator.setText("0");

        btnDEL.setBackground(new java.awt.Color(29, 28, 28));
        btnDEL.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnDEL.setForeground(new java.awt.Color(255, 255, 255));
        btnDEL.setText("DEL");
        btnDEL.setBorder(null);
        btnDEL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDEL.setSelected(true);
        btnDEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDELActionPerformed(evt);
            }
        });

        btnAC.setBackground(new java.awt.Color(29, 28, 28));
        btnAC.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnAC.setForeground(new java.awt.Color(255, 255, 255));
        btnAC.setText("AC");
        btnAC.setBorder(null);
        btnAC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAC.setSelected(true);
        btnAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnACActionPerformed(evt);
            }
        });

        btnPerc.setBackground(new java.awt.Color(29, 28, 28));
        btnPerc.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnPerc.setForeground(new java.awt.Color(255, 255, 255));
        btnPerc.setText("%");
        btnPerc.setBorder(null);
        btnPerc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPerc.setSelected(true);
        btnPerc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPercActionPerformed(evt);
            }
        });

        btnDiv.setBackground(new java.awt.Color(29, 28, 28));
        btnDiv.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnDiv.setForeground(new java.awt.Color(255, 255, 255));
        btnDiv.setText("÷");
        btnDiv.setBorder(null);
        btnDiv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDiv.setSelected(true);
        btnDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivActionPerformed(evt);
            }
        });

        btn7.setBackground(new java.awt.Color(29, 28, 28));
        btn7.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btn7.setForeground(new java.awt.Color(255, 255, 255));
        btn7.setText("7");
        btn7.setBorder(null);
        btn7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn7.setSelected(true);
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn8.setBackground(new java.awt.Color(29, 28, 28));
        btn8.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btn8.setForeground(new java.awt.Color(255, 255, 255));
        btn8.setText("8");
        btn8.setBorder(null);
        btn8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn8.setSelected(true);
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn9.setBackground(new java.awt.Color(29, 28, 28));
        btn9.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btn9.setForeground(new java.awt.Color(255, 255, 255));
        btn9.setText("9");
        btn9.setBorder(null);
        btn9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn9.setSelected(true);
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btnMenos.setBackground(new java.awt.Color(29, 28, 28));
        btnMenos.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnMenos.setForeground(new java.awt.Color(255, 255, 255));
        btnMenos.setText("-");
        btnMenos.setBorder(null);
        btnMenos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenos.setSelected(true);
        btnMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenosActionPerformed(evt);
            }
        });

        btn4.setBackground(new java.awt.Color(29, 28, 28));
        btn4.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btn4.setForeground(new java.awt.Color(255, 255, 255));
        btn4.setText("4");
        btn4.setBorder(null);
        btn4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn4.setSelected(true);
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btnMais.setBackground(new java.awt.Color(29, 28, 28));
        btnMais.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnMais.setForeground(new java.awt.Color(255, 255, 255));
        btnMais.setText("+");
        btnMais.setBorder(null);
        btnMais.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMais.setSelected(true);
        btnMais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaisActionPerformed(evt);
            }
        });

        btn5.setBackground(new java.awt.Color(29, 28, 28));
        btn5.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btn5.setForeground(new java.awt.Color(255, 255, 255));
        btn5.setText("5");
        btn5.setBorder(null);
        btn5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn5.setSelected(true);
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn6.setBackground(new java.awt.Color(29, 28, 28));
        btn6.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btn6.setForeground(new java.awt.Color(255, 255, 255));
        btn6.setText("6");
        btn6.setBorder(null);
        btn6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn6.setSelected(true);
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn1.setBackground(new java.awt.Color(29, 28, 28));
        btn1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btn1.setForeground(new java.awt.Color(255, 255, 255));
        btn1.setText("1");
        btn1.setBorder(null);
        btn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn1.setSelected(true);
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setBackground(new java.awt.Color(29, 28, 28));
        btn2.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btn2.setForeground(new java.awt.Color(255, 255, 255));
        btn2.setText("2");
        btn2.setBorder(null);
        btn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn2.setSelected(true);
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setBackground(new java.awt.Color(29, 28, 28));
        btn3.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btn3.setForeground(new java.awt.Color(255, 255, 255));
        btn3.setText("3");
        btn3.setBorder(null);
        btn3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn3.setSelected(true);
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn0.setBackground(new java.awt.Color(29, 28, 28));
        btn0.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btn0.setForeground(new java.awt.Color(255, 255, 255));
        btn0.setText("0");
        btn0.setBorder(null);
        btn0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn0.setSelected(true);
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });

        btnIgual.setBackground(new java.awt.Color(51, 51, 51));
        btnIgual.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnIgual.setForeground(new java.awt.Color(255, 255, 255));
        btnIgual.setText("=");
        btnIgual.setBorder(null);
        btnIgual.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIgual.setSelected(true);
        btnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIgualActionPerformed(evt);
            }
        });

        btnPonto.setBackground(new java.awt.Color(29, 28, 28));
        btnPonto.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnPonto.setForeground(new java.awt.Color(255, 255, 255));
        btnPonto.setText(",");
        btnPonto.setBorder(null);
        btnPonto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPonto.setSelected(true);
        btnPonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPontoActionPerformed(evt);
            }
        });

        btnMulti.setBackground(new java.awt.Color(29, 28, 28));
        btnMulti.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnMulti.setForeground(new java.awt.Color(255, 255, 255));
        btnMulti.setText("×");
        btnMulti.setBorder(null);
        btnMulti.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMulti.setSelected(true);
        btnMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TelaNormalLayout = new javax.swing.GroupLayout(TelaNormal);
        TelaNormal.setLayout(TelaNormalLayout);
        TelaNormalLayout.setHorizontalGroup(
            TelaNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inputCalculator, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(TelaNormalLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(TelaNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TelaNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(TelaNormalLayout.createSequentialGroup()
                            .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(TelaNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TelaNormalLayout.createSequentialGroup()
                                .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(TelaNormalLayout.createSequentialGroup()
                                .addComponent(btnAC, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPerc, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDEL, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(TelaNormalLayout.createSequentialGroup()
                        .addGroup(TelaNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(TelaNormalLayout.createSequentialGroup()
                                .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPonto, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TelaNormalLayout.createSequentialGroup()
                                .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(TelaNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMais, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TelaNormalLayout.setVerticalGroup(
            TelaNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelaNormalLayout.createSequentialGroup()
                .addComponent(inputCalculator, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TelaNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPerc, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(TelaNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAC, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDEL, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TelaNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(TelaNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TelaNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(TelaNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TelaNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(TelaNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnMais, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TelaNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(TelaNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPonto, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnDEL.putClientProperty(FlatClientProperties.STYLE, "arc: 12");
        btnAC.putClientProperty(FlatClientProperties.STYLE, "arc: 12");
        btnPerc.putClientProperty(FlatClientProperties.STYLE, "arc: 12");
        btnDiv.putClientProperty(FlatClientProperties.STYLE, "arc: 12");
        btn7.putClientProperty(FlatClientProperties.STYLE, "arc: 12");
        btn8.putClientProperty(FlatClientProperties.STYLE, "arc: 12");
        btn9.putClientProperty(FlatClientProperties.STYLE, "arc: 12");
        btnMenos.putClientProperty(FlatClientProperties.STYLE, "arc: 12");
        btn4.putClientProperty(FlatClientProperties.STYLE, "arc: 12");
        btnMais.putClientProperty(FlatClientProperties.STYLE, "arc: 12");
        btn5.putClientProperty(FlatClientProperties.STYLE, "arc: 12");
        btn6.putClientProperty(FlatClientProperties.STYLE, "arc: 12");
        btn1.putClientProperty(FlatClientProperties.STYLE, "arc: 12");
        btn2.putClientProperty(FlatClientProperties.STYLE, "arc: 12");
        btn3.putClientProperty(FlatClientProperties.STYLE, "arc: 12");
        btn0.putClientProperty(FlatClientProperties.STYLE, "arc: 12");
        btnIgual.putClientProperty(FlatClientProperties.STYLE, "arc: 12");
        btnPonto.putClientProperty(FlatClientProperties.STYLE, "arc: 12");
        btnMulti.putClientProperty(FlatClientProperties.STYLE, "arc: 12");

        CalculadoraMenu.addTab("Normal", TelaNormal);
        CalculadoraMenu.addTab("Científica", TelaCientifica);
        CalculadoraMenu.addTab("IMC", TelaIMC);

        btnSobre.setText("Sobre");
        btnSobre.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnSobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSobreMouseClicked(evt);
            }
        });
        MenuBar.add(btnSobre);

        btnAjuda.setText("Ajuda");
        btnAjuda.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnAjuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAjudaMouseClicked(evt);
            }
        });
        MenuBar.add(btnAjuda);

        btnHistorico.setText("Histórico");
        btnHistorico.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnHistorico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHistoricoMouseClicked(evt);
            }
        });
        MenuBar.add(btnHistorico);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CalculadoraMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CalculadoraMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void setEnabledIfDivZero(Boolean value) {
        btnPerc.setEnabled(value);
        btnMais.setEnabled(value);
        btnMulti.setEnabled(value);
        btnDiv.setEnabled(value);
        btnMenos.setEnabled(value);
        btnMais.setEnabled(value);
        btnPonto.setEnabled(value);
    }

    private void btnMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiActionPerformed
        calculadoraNormal.onClickOperator(evt, () -> setEnabledIfDivZero(true));
    }//GEN-LAST:event_btnMultiActionPerformed

    private void btnPontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPontoActionPerformed
        calculadoraNormal.onClickPoint(evt, () -> setEnabledIfDivZero(true));
    }//GEN-LAST:event_btnPontoActionPerformed

    private void btnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIgualActionPerformed
        calculadoraNormal.onClickResult(evt, () -> setEnabledIfDivZero(false));
    }//GEN-LAST:event_btnIgualActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        calculadoraNormal.onClickNumber(evt, () -> setEnabledIfDivZero(true));
    }//GEN-LAST:event_btn0ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        calculadoraNormal.onClickNumber(evt, () -> setEnabledIfDivZero(true));
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        calculadoraNormal.onClickNumber(evt, () -> setEnabledIfDivZero(true));
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        calculadoraNormal.onClickNumber(evt, () -> setEnabledIfDivZero(true));
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        calculadoraNormal.onClickNumber(evt, () -> setEnabledIfDivZero(true));
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        calculadoraNormal.onClickNumber(evt, () -> setEnabledIfDivZero(true));
    }//GEN-LAST:event_btn5ActionPerformed

    private void btnMaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaisActionPerformed
        calculadoraNormal.onClickOperator(evt, () -> setEnabledIfDivZero(true));
    }//GEN-LAST:event_btnMaisActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        calculadoraNormal.onClickNumber(evt, () -> setEnabledIfDivZero(true));
    }//GEN-LAST:event_btn4ActionPerformed

    private void btnMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenosActionPerformed
        calculadoraNormal.onClickOperator(evt, () -> setEnabledIfDivZero(true));
    }//GEN-LAST:event_btnMenosActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        calculadoraNormal.onClickNumber(evt, () -> setEnabledIfDivZero(true));
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        calculadoraNormal.onClickNumber(evt, () -> setEnabledIfDivZero(true));
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        calculadoraNormal.onClickNumber(evt, () -> setEnabledIfDivZero(true));
    }//GEN-LAST:event_btn7ActionPerformed

    private void btnDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivActionPerformed
        calculadoraNormal.onClickOperator(evt, () -> setEnabledIfDivZero(true));
    }//GEN-LAST:event_btnDivActionPerformed

    private void btnPercActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPercActionPerformed
        calculadoraNormal.onClickOperator(evt, () -> setEnabledIfDivZero(true));
    }//GEN-LAST:event_btnPercActionPerformed

    private void btnACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnACActionPerformed
        calculadoraNormal.onClickAC(() -> setEnabledIfDivZero(true));
    }//GEN-LAST:event_btnACActionPerformed

    private void btnDELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDELActionPerformed
        calculadoraNormal.onClickDelete(() -> setEnabledIfDivZero(true));
    }//GEN-LAST:event_btnDELActionPerformed

    private void btnHistoricoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHistoricoMouseClicked
        TelaHistorico telaHistorico = new TelaHistorico(this, true, calculadoraNormal.getHistory());
        telaHistorico.setVisible(true);
    }//GEN-LAST:event_btnHistoricoMouseClicked

    private void btnAjudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAjudaMouseClicked
        TelaAjuda telaAjuda = new TelaAjuda(this, true);
        telaAjuda.setVisible(true);
    }//GEN-LAST:event_btnAjudaMouseClicked

    private void btnSobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSobreMouseClicked
        TelaSobre telaSobre = new TelaSobre(this, true);
        telaSobre.setVisible(true);
    }//GEN-LAST:event_btnSobreMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        FlatMacDarkLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaCalculadora telaCalculadora = new TelaCalculadora();
                telaCalculadora.setVisible(true);
                //telaCalculadora.setTitle("Calculadora");

                telaCalculadora.setCalculadoraNormal(new CalculadoraNormal());
                CalculadoraNormal calculadoraNormal = telaCalculadora.getCalculadoraNormal();

                calculadoraNormal.setDisplay(telaCalculadora.inputCalculator);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane CalculadoraMenu;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JTabbedPane TelaCientifica;
    private javax.swing.JTabbedPane TelaIMC;
    private javax.swing.JPanel TelaNormal;
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnAC;
    private javax.swing.JMenu btnAjuda;
    private javax.swing.JButton btnDEL;
    private javax.swing.JButton btnDiv;
    private javax.swing.JMenu btnHistorico;
    private javax.swing.JButton btnIgual;
    private javax.swing.JButton btnMais;
    private javax.swing.JButton btnMenos;
    private javax.swing.JButton btnMulti;
    private javax.swing.JButton btnPerc;
    private javax.swing.JButton btnPonto;
    private javax.swing.JMenu btnSobre;
    public javax.swing.JTextField inputCalculator;
    // End of variables declaration//GEN-END:variables
}
